# echo -n mongouser | base64 output: bW9uZ291c2Vy
# echo -n mongopassword | base64 output: bW9uZ29wYXNzd29yZA==
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
